sudo: required
language: generic

dist: Focal
jdk: 
  openjdk11
  oraclejdk11

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 
  components:
    - tools
    - build-tools-30.0.2
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  matrix:
    - EMULATOR_API=22
    - EMULATOR_API=25
 
before_install:
  - chmod +x gradlew
  - chmod +x android-wait-for-emulator
  - echo $JAVA_HOME
  
install:
  - export ANDROID_HOME=~/android-sdk-linux
  - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/cmdline-tools/bin:${ANDROID_HOME}/bin:${ANDROID_HOME}/cmdline-tools/tools/bin
  - chmod +x ${ANDROID_HOME}/cmdline-tools/bin/sdkmanager
  - yes | sudo sdkmanager --licenses
  - ./gradlew dependencies || true
  - ./gradle assemble || true
  - sdkmanager --list | head -20
  - sdkmanager "system-images;android-$EMULATOR_API;$ABI" > /dev/null

before_script:
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API;$ABI"
  - $ANDROID_HOME/emulator/emulator -avd test -no-window &
  - bash android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./gradlew connectedAndroidTest -PdisablePreDex
