sudo: required
language: android

dist: Focal
jdk: openjdk11
    
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 
  components:
    - tools
    - build-tools-30.0.2
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
 
before_script:
  - which sdkmanager
  - export HERE=${PWD}
  - mkdir .android
  - touch .android/repositories.cfg
  - mkdir .android/avd
  - sdkmanager --sdk_root=/usr/local/android-sdk/tools/bin/ "tools"
  - sdkmanager --sdk_root=/usr/local/android-sdk/tools/bin/ "system-images;android-30;google_apis;x86"
  - sdkmanager --sdk_root=/usr/local/android-sdk/tools/bin/ "build-tools;30.0.2"
  - sdkmanager --sdk_root=/usr/local/android-sdk/tools/bin/ "platforms;android-30"
  - sdkmanager --sdk_root=/usr/local/android-sdk/tools/bin/ --licenses
  - export PATH=$PATH:/usr/local/android-sdk/tools/bin/
  - chmod +x ./gradlew
  - cd /usr/local/android-sdk/tools/bin/
  - ls -l
  - ./sdkmanager --sdk_root=/usr/local/android-sdk/tools/bin/ --list
  - cd $HERE

script:
  - ./gradlew assembleDebug
