sudo: required
language: android

dist: Focal
jdk: openjdk11
    
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 
  components:
    - tools
    - build-tools-30.0.2
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
 
before_script:
  - sudo apt-get update --yes
  - sudo apt-get install --yes wget tar unzip lib32stdc++6 lib32z1
  - echo $ANDROID_SDK_ROOT
  - which sdkmanager
  - export ANDROID_HOME=${PWD}/android-home
  - export ANDROID_SDK_ROOT=$ANDROID_HOME
  - export HERE=${PWD}
  - mkdir .android
  - touch .android/repositories.cfg
  - mkdir .android/avd
  - install -d $ANDROID_HOME
  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
  - pushd $ANDROID_HOME
  - unzip -d cmdline-tools cmdline-tools.zip
  - popd
  - ls -l ${ANDROID_HOME}
  - ls -l ${ANDROID_HOME}/cmdline-tools/
  - mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
  - ls -l ${ANDROID_HOME}/cmdline-tools/latest/bin/
  - export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/latest/bin/
  - chmod +x ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager
  - sdkmanager --version
  - set +o pipefail
  - yes | sdkmanager --sdk_root=${ANDROID_HOME}/cmdline-tools/latest/bin/ --licenses
  - set -o pipefail
  - sdkmanager --sdk_root=${ANDROID_HOME}/cmdline-tools/latest/bin/ --install "tools"
  - sdkmanager --sdk_root=${ANDROID_HOME}/cmdline-tools/latest/bin/ --install "system-images;android-30;google_apis;x86"
  - sdkmanager --sdk_root=${ANDROID_HOME}/cmdline-tools/latest/bin/ --install "build-tools;30.0.2"
  - sdkmanager --sdk_root=${ANDROID_HOME}/cmdline-tools/latest/bin/ --install "platforms;android-30"
  - sdkmanager --sdk_root=${ANDROID_HOME}/cmdline-tools/latest/bin/ --licenses
  - export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/latest/bin/platform-tools/
  - chmod +x ./gradlew
  - cd ${ANDROID_HOME}/cmdline-tools/latest/bin/
  - ls -l
  - ./sdkmanager --sdk_root=${ANDROID_HOME}/cmdline-tools/latest/bin/ --list
  - cd $HERE

script:
  - ./gradlew assembleDebug
